name: coffee_now
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.2.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  equatable: ^2.0.5
  image_picker: ^1.0.2
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  lottie: ^2.5.0
  shimmer: ^3.0.0
  permission_handler: ^10.4.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  geolocator: ^9.0.2
  google_sign_in: ^6.1.4
  flutter_phoenix: ^1.1.1
  dartz: ^0.10.1
  firebase_storage: ^11.2.5
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^9.3.0
  flutter_svg: ^2.0.7
  google_maps_flutter: ^2.4.0
  geocoding: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  flutter_rating_bar: ^4.0.1
  skeletons: ^0.0.3
  pin_code_fields: ^7.3.0
  flutter_gen: ^5.3.1
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  firebase_crashlytics: ^3.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
         
    - family: Bebas Neue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
       

  
