// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LvcvpdtGHT-pV2GvHVHiHlwFRhJ0c-4',
    appId: '1:342408361859:web:b8e2d4cfe553f0aca7e8b6',
    messagingSenderId: '342408361859',
    projectId: 'coffee-now-24a13',
    authDomain: 'coffee-now-24a13.firebaseapp.com',
    storageBucket: 'coffee-now-24a13.appspot.com',
    measurementId: 'G-6EGMY217VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKtYpnqdoL_ZZMqkEFTWd3eA3O_Rx__Qo',
    appId: '1:342408361859:android:2a71145ac60f384fa7e8b6',
    messagingSenderId: '342408361859',
    projectId: 'coffee-now-24a13',
    storageBucket: 'coffee-now-24a13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzohma9iCCp4RWBH4lctQleRPf0EPdz6U',
    appId: '1:342408361859:ios:7b1653274e4b9a22a7e8b6',
    messagingSenderId: '342408361859',
    projectId: 'coffee-now-24a13',
    storageBucket: 'coffee-now-24a13.appspot.com',
    iosClientId: '342408361859-p8m1j4qtfupbjtbk4n62v8db9sv7mtet.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzohma9iCCp4RWBH4lctQleRPf0EPdz6U',
    appId: '1:342408361859:ios:94acfda23ecab419a7e8b6',
    messagingSenderId: '342408361859',
    projectId: 'coffee-now-24a13',
    storageBucket: 'coffee-now-24a13.appspot.com',
    iosClientId: '342408361859-ltenr79vv9rvk0rusq654a2g8eatldka.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeNow.RunnerTests',
  );
}
